# Motion Data Configuration
# 可以在这里列出所有要加载的 motion 数据文件
# 支持绝对路径和相对路径（相对于本配置文件所在目录）

# 注意：所有 motion 文件必须具有相同的骨骼结构（相同的 body 和 dof 数量）
# /home/hz/datasets/g1_amp_nzp 目录下的 walk 和 run 文件：25 bodies, 29 dofs

motion_files:
  # Walk 数据
  - /home/hz/g1/humanoid_amp/motions/custom_motion.npz
  # - /home/hz/datasets/g1_amp_nzp/walk1_subject1.npz
  # - /home/hz/datasets/g1_amp_nzp/walk1_subject2.npz
  # - /home/hz/datasets/g1_amp_nzp/walk1_subject5.npz
  # - /home/hz/datasets/g1_amp_nzp/walk2_subject1.npz
  # - /home/hz/datasets/g1_amp_nzp/walk2_subject3.npz
  # - /home/hz/datasets/g1_amp_nzp/walk2_subject4.npz
  # - /home/hz/datasets/g1_amp_nzp/walk3_subject1.npz
  # - /home/hz/datasets/g1_amp_nzp/walk3_subject2.npz
  # - /home/hz/datasets/g1_amp_nzp/walk3_subject3.npz
  # - /home/hz/datasets/g1_amp_nzp/walk3_subject4.npz
  # - /home/hz/datasets/g1_amp_nzp/walk3_subject5.npz
  # - /home/hz/datasets/g1_amp_nzp/walk4_subject1.npz

  # # Run 数据
  # - /home/hz/datasets/g1_amp_nzp/run1_subject2.npz
  # - /home/hz/datasets/g1_amp_nzp/run1_subject5.npz
  # - /home/hz/datasets/g1_amp_nzp/run2_subject1.npz
  # - /home/hz/datasets/g1_amp_nzp/run2_subject4.npz


